#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
effect_reproducer.py — 效果复现引擎
====================================

将 VRS v2 (video_effect_analyzer_v2.py) 的分析结果转化为 After Effects
可执行的 ExtendScript (JSX) 脚本，实现视频效果的自动化复现。

核心流程：
  VRS v2 JSON → 图层规划 → 效果参数映射 → JSX 脚本生成 → MCP/文件输出

依赖：
  - effect_registry.py（matchName 映射 + 参数数据库）
  - effect_knowledge_graph.py（效果关系 + 风格配方）

用法：
    from effect_reproducer import EffectReproducer

    reproducer = EffectReproducer()
    jsx = reproducer.generate_jsx(vrs_analysis_result)
    # 或导出为文件
    reproducer.export_jsx(vrs_analysis_result, "output/reproduce.jsx")
"""
from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from effect_registry import (
    EFFECT_PARAMS_DB,
    EFFECT_CATEGORIES,
    KEYWORD_TO_EFFECT_MAP,
    get_effect_matchname,
    get_effect_params,
)

# ---------------------------------------------------------------------------
# 混合模式映射（VRS 输出 → AE ExtendScript 常量）
# ---------------------------------------------------------------------------
BLEND_MODE_MAP: Dict[str, str] = {
    "NORMAL": "BlendingMode.NORMAL",
    "SCREEN": "BlendingMode.SCREEN",
    "MULTIPLY": "BlendingMode.MULTIPLY",
    "ADD": "BlendingMode.ADD",
    "OVERLAY": "BlendingMode.OVERLAY",
    "SOFT_LIGHT": "BlendingMode.SOFT_LIGHT",
    "HARD_LIGHT": "BlendingMode.HARD_LIGHT",
    "DIFFERENCE": "BlendingMode.DIFFERENCE",
    "COLOR": "BlendingMode.COLOR",
    "LUMINOSITY": "BlendingMode.LUMINOSITY",
}

# 图层角色 → 图层类型
LAYER_ROLE_MAP: Dict[str, str] = {
    "background_layer": "footage",
    "main_subject": "footage",
    "adjustment_layer": "adjustment",
    "glow_layer": "solid",
    "particle_layer": "solid",
    "text_layer": "text",
    "vignette_layer": "adjustment",
}

# 图层渲染顺序（从底到顶）
LAYER_ORDER: List[str] = [
    "background_layer",
    "main_subject",
    "adjustment_layer",
    "glow_layer",
    "particle_layer",
    "text_layer",
    "vignette_layer",
]


class EffectReproducer:
    """效果复现引擎 — 将 VRS 分析结果转化为 AE JSX 脚本。"""

    def __init__(self, default_width: int = 1920, default_height: int = 1080,
                 default_fps: float = 30.0, default_duration: float = 10.0):
        self.default_width = default_width
        self.default_height = default_height
        self.default_fps = default_fps
        self.default_duration = default_duration

    # =========================================================================
    # 公共入口
    # =========================================================================

    def generate_jsx(
        self,
        analysis: Dict[str, Any],
        comp_name: str = "Reproduce_Comp",
        include_comments: bool = True,
    ) -> str:
        """根据 VRS v2 分析结果生成完整 JSX 脚本。

        Args:
            analysis: VRS v2 的分析结果（merged 或 vision_result）
            comp_name: AE 合成名称
            include_comments: 是否在 JSX 中包含注释

        Returns:
            完整的 ExtendScript 脚本字符串
        """
        # 1. 解析分析结果
        effects = self._extract_effects(analysis)
        blend_modes = self._extract_blend_modes(analysis)
        comp_structure = self._extract_comp_structure(analysis)
        style_tags = self._extract_style_tags(analysis)
        video_info = self._extract_video_info(analysis)

        # 2. 按图层角色分组效果
        layer_groups = self._group_effects_by_layer(effects)

        # 3. 生成 JSX
        lines: List[str] = []
        if include_comments:
            lines.append("// ============================================")
            lines.append(f"// Auto-generated by EffectReproducer")
            lines.append(f"// Time: {datetime.now().isoformat()}")
            lines.append(f"// Style: {', '.join(style_tags) if style_tags else 'N/A'}")
            lines.append(f"// Effects: {len(effects)}")
            lines.append("// ============================================")
            lines.append("")

        # 合成创建
        w = video_info.get("width", self.default_width)
        h = video_info.get("height", self.default_height)
        fps = video_info.get("fps", self.default_fps)
        dur = video_info.get("duration", self.default_duration)

        lines.append(f'var comp = app.project.items.addComp("{comp_name}", {w}, {h}, 1, {dur}, {fps});')
        lines.append("")

        # 4. 按图层顺序生成
        for role in LAYER_ORDER:
            if role not in layer_groups:
                continue
            group = layer_groups[role]
            layer_type = LAYER_ROLE_MAP.get(role, "solid")

            if include_comments:
                lines.append(f"// --- Layer: {role} ({len(group['effects'])} effects) ---")

            # 创建图层
            if layer_type == "adjustment":
                lines.append(f'var layer = comp.layers.addSolid([1, 1, 1], "{role}", {w}, {h}, 1, {dur});')
                lines.append("layer.adjustmentLayer = true;")
            elif layer_type == "text":
                lines.append(f'var layer = comp.layers.addText("{role}");')
            else:
                lines.append(f'var layer = comp.layers.addSolid([0, 0, 0], "{role}", {w}, {h}, 1, {dur});')

            # 设置混合模式
            blend = group.get("blend_mode")
            if blend and blend in BLEND_MODE_MAP:
                lines.append(f"layer.blendingMode = {BLEND_MODE_MAP[blend]};")

            # 设置不透明度
            opacity = group.get("opacity")
            if opacity is not None:
                lines.append(f"layer.opacity.setValue({opacity});")

            # 添加效果
            for eff in group["effects"]:
                jsx_lines = self._generate_effect_jsx(eff, indent="  ")
                lines.extend(jsx_lines)

            lines.append("")

        # 5. 收尾
        lines.append("comp.openInViewer();")
        lines.append('alert("Effect reproduction complete: ' + comp_name + '");')

        return "\n".join(lines)

    def export_jsx(self, analysis: Dict[str, Any], output_path: str,
                   comp_name: str = "Reproduce_Comp") -> str:
        """生成 JSX 并写入文件。

        Returns:
            输出文件路径
        """
        jsx = self.generate_jsx(analysis, comp_name=comp_name)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(jsx, encoding="utf-8")
        return str(path)

    def generate_confidence_report(self, analysis: Dict[str, Any]) -> Dict[str, Any]:
        """生成置信度报告 — 标注哪些效果可自动复现、哪些需手动调整。

        Returns:
            {
                "auto_reproducible": [...],   # 高置信度，可直接应用
                "needs_review": [...],        # 中置信度，建议检查
                "manual_only": [...],         # 低置信度/第三方插件，需手动
                "total_effects": int,
                "auto_rate": float,           # 自动复现率
            }
        """
        effects = self._extract_effects(analysis)
        auto = []
        review = []
        manual = []

        for eff in effects:
            match_name = eff.get("matchName", "")
            confidence = eff.get("confidence", 0.5)
            name = eff.get("name", "unknown")

            # 判断是否可直接应用
            has_params = match_name in EFFECT_PARAMS_DB
            is_builtin = match_name.startswith("ADBE ") or match_name.startswith("CC ")
            is_third_party = match_name.startswith("VC ") or match_name.startswith("TC ") or \
                             match_name.startswith("RB ") or match_name.startswith("BCC ") or \
                             match_name.startswith("E3D")

            if confidence >= 0.7 and (is_builtin or has_params):
                auto.append({"name": name, "matchName": match_name,
                             "confidence": confidence, "has_params": has_params})
            elif confidence >= 0.4:
                review.append({"name": name, "matchName": match_name,
                               "confidence": confidence, "reason": "medium_confidence"})
            else:
                manual.append({"name": name, "matchName": match_name,
                               "confidence": confidence,
                               "reason": "third_party_plugin" if is_third_party else "low_confidence"})

        total = len(effects)
        return {
            "auto_reproducible": auto,
            "needs_review": review,
            "manual_only": manual,
            "total_effects": total,
            "auto_rate": len(auto) / max(total, 1),
        }

    # =========================================================================
    # 内部方法
    # =========================================================================

    def _extract_effects(self, analysis: Dict[str, Any]) -> List[Dict[str, Any]]:
        """从分析结果中提取效果列表（兼容多种结果结构）。"""
        # 尝试 merged 结构
        merged = analysis.get("merged", {})
        if merged and "effects" in merged:
            return merged["effects"]

        # 尝试 vision_result 结构
        vision = analysis.get("vision_result", {})
        agg = vision.get("aggregated_effects", [])
        if agg:
            return agg

        # 尝试 frame_analyses
        frame_analyses = vision.get("frame_analyses", [])
        all_effects = []
        for fa in frame_analyses:
            if fa.get("success") and "effects" in fa:
                all_effects.extend(fa["effects"])
        if all_effects:
            return all_effects

        # 尝试 batch_analyses
        batch_analyses = vision.get("batch_analyses", [])
        for ba in batch_analyses:
            if "effects" in ba:
                all_effects.extend(ba["effects"])
        if all_effects:
            return all_effects

        # 顶层 effects
        if "effects" in analysis:
            return analysis["effects"]

        return []

    def _extract_blend_modes(self, analysis: Dict[str, Any]) -> List[str]:
        merged = analysis.get("merged", analysis.get("vision_result", analysis))
        return merged.get("blend_modes_detected", [])

    def _extract_comp_structure(self, analysis: Dict[str, Any]) -> Dict[str, Any]:
        merged = analysis.get("merged", analysis.get("vision_result", analysis))
        return merged.get("composition_structure", {})

    def _extract_style_tags(self, analysis: Dict[str, Any]) -> List[str]:
        merged = analysis.get("merged", analysis.get("vision_result", analysis))
        return merged.get("style_tags", [])

    def _extract_video_info(self, analysis: Dict[str, Any]) -> Dict[str, Any]:
        cv = analysis.get("cv_result", {})
        basic = cv.get("basic_info", {})
        return {
            "width": basic.get("width", self.default_width),
            "height": basic.get("height", self.default_height),
            "fps": basic.get("fps", self.default_fps),
            "duration": basic.get("duration", self.default_duration),
        }

    def _group_effects_by_layer(
        self, effects: List[Dict[str, Any]]
    ) -> Dict[str, Dict[str, Any]]:
        """按图层角色分组效果，并分配混合模式。"""
        groups: Dict[str, Dict[str, Any]] = {}

        for eff in effects:
            role = eff.get("layer_role", "adjustment_layer")
            if role not in groups:
                groups[role] = {"effects": [], "blend_mode": None, "opacity": None}
            groups[role]["effects"].append(eff)

        # 为特定角色分配默认混合模式
        if "glow_layer" in groups and not groups["glow_layer"]["blend_mode"]:
            groups["glow_layer"]["blend_mode"] = "SCREEN"
            groups["glow_layer"]["opacity"] = 80
        if "particle_layer" in groups and not groups["particle_layer"]["blend_mode"]:
            groups["particle_layer"]["blend_mode"] = "ADD"
            groups["particle_layer"]["opacity"] = 90
        if "vignette_layer" in groups and not groups["vignette_layer"]["blend_mode"]:
            groups["vignette_layer"]["blend_mode"] = "MULTIPLY"
            groups["vignette_layer"]["opacity"] = 60

        return groups

    def _generate_effect_jsx(self, effect: Dict[str, Any], indent: str = "  ") -> List[str]:
        """为单个效果生成 JSX 代码行。"""
        lines: List[str] = []
        match_name = effect.get("matchName", "")
        effect_name = effect.get("name", match_name)
        params = effect.get("params", {})
        intensity = effect.get("intensity", 50)

        if not match_name:
            return lines

        # 效果名（用于 AE 中添加）
        display = effect_name or match_name
        lines.append(f'{indent}// Effect: {display} (intensity: {intensity})')

        # 检查是否在参数数据库中
        param_db = get_effect_params(match_name)

        if match_name.startswith("ADBE ") or match_name.startswith("CC "):
            # 内置效果 — 直接通过 matchName 添加
            lines.append(f'{indent}var eff = layer.Effects.addProperty("{match_name}");')
            lines.append(f'{indent}eff.name = "{display}";')

            # 设置参数
            for param_name, param_value in params.items():
                jsx_val = self._python_to_jsx_value(param_value, param_db, param_name)
                lines.append(f'{indent}eff.property("{param_name}").setValue({jsx_val});')

        elif match_name.startswith("VC ") or match_name.startswith("TC ") or \
             match_name.startswith("RB ") or match_name.startswith("BCC ") or \
             match_name.startswith("E3D"):
            # 第三方插件 — 生成注释提示（需要用户手动安装插件）
            lines.append(f'{indent}// [WARNING] Third-party plugin required: {match_name}')
            lines.append(f'{indent}// Install the plugin, then manually add: {display}')
            for param_name, param_value in params.items():
                lines.append(f'{indent}//   {param_name} = {param_value}')
        else:
            # 未知效果 — 尝试通过名称添加
            lines.append(f'{indent}// [INFO] Unknown effect: {match_name}, attempting by name')
            lines.append(f'{indent}var eff = layer.Effects.addProperty("{match_name}");')
            for param_name, param_value in params.items():
                jsx_val = self._python_to_jsx_value(param_value, param_db, param_name)
                lines.append(f'{indent}eff.property("{param_name}").setValue({jsx_val});')

        return lines

    def _python_to_jsx_value(
        self, value: Any, param_db: Optional[Dict], param_name: str = ""
    ) -> str:
        """将 Python 值转为 JSX 可接受的字符串。"""
        if isinstance(value, bool):
            return "true" if value else "false"
        elif isinstance(value, (int, float)):
            # 范围钳制
            if param_db and param_name:
                pdef = param_db.get("params", {}).get(param_name, {})
                if "min" in pdef:
                    value = max(pdef["min"], value)
                if "max" in pdef:
                    value = min(pdef["max"], value)
            return str(value)
        elif isinstance(value, str):
            return f'"{value}"'
        elif isinstance(value, list):
            # 颜色 [r, g, b, a] 或点 [x, y]
            if len(value) == 4:
                return f"[{value[0]}, {value[1]}, {value[2]}, {value[3]}]"
            elif len(value) == 2:
                return f"[{value[0]}, {value[1]}]"
            else:
                return f"[{', '.join(str(v) for v in value)}]"
        elif isinstance(value, dict):
            return json.dumps(value)
        else:
            return str(value)


# ============================================================================
# CLI 测试入口
# ============================================================================

if __name__ == "__main__":
    # 模拟 VRS v2 分析结果
    mock_analysis = {
        "cv_result": {
            "basic_info": {"width": 1920, "height": 1080, "fps": 30, "duration": 15},
        },
        "merged": {
            "effects": [
                {
                    "type": "glow",
                    "name": "Deep Glow",
                    "matchName": "RB Deep Glow",
                    "intensity": 75,
                    "confidence": 0.85,
                    "params": {"Threshold": 50, "Radius": 100, "Intensity": 1.5},
                    "layer_role": "adjustment_layer",
                },
                {
                    "type": "blur",
                    "name": "Gaussian Blur",
                    "matchName": "ADBE Gaussian Blur 2",
                    "intensity": 30,
                    "confidence": 0.9,
                    "params": {"Blurriness": 15},
                    "layer_role": "background_layer",
                },
                {
                    "type": "color",
                    "name": "Lumetri Color",
                    "matchName": "ADBE Lumetri Color",
                    "intensity": 60,
                    "confidence": 0.8,
                    "params": {
                        "Temperature": 10, "Tint": -5, "Exposure": 0.3,
                        "Contrast": 20, "Saturation": 15,
                    },
                    "layer_role": "adjustment_layer",
                },
                {
                    "type": "noise",
                    "name": "Add Grain",
                    "matchName": "ADBE Add Grain",
                    "intensity": 40,
                    "confidence": 0.7,
                    "params": {"Amount": 25, "Size": 0.5},
                    "layer_role": "adjustment_layer",
                },
                {
                    "type": "particle",
                    "name": "Particular",
                    "matchName": "TC Particular",
                    "intensity": 80,
                    "confidence": 0.75,
                    "params": {"Particles/Sec": 200, "Longevity": 4, "Size": 5},
                    "layer_role": "particle_layer",
                },
            ],
            "blend_modes_detected": ["SCREEN", "ADD"],
            "composition_structure": {
                "main_subject": True,
                "adjustment_layer": True,
                "particle_layer": True,
                "background_layer": True,
            },
            "style_tags": ["高燃", "赛博朋克"],
        },
    }

    reproducer = EffectReproducer()

    # 生成 JSX
    jsx = reproducer.generate_jsx(mock_analysis, comp_name="Cyberpunk_Test")
    print("=" * 60)
    print("Generated JSX:")
    print("=" * 60)
    print(jsx)

    # 置信度报告
    report = reproducer.generate_confidence_report(mock_analysis)
    print("\n" + "=" * 60)
    print("Confidence Report:")
    print("=" * 60)
    print(json.dumps(report, indent=2, ensure_ascii=False))
