"""
ae_to_blender_bridge.py - AE 工程 → Blender 3D 场景桥接器

将 AE 分析结果转换为 Blender Python 脚本，实现：
- 合成层级 → Collection 层级
- 图层 → Empty/图像平面
- 效果信息 → 注释/自定义属性
- 摄像机参数 → Blender Camera
- PSD 图层 → 图像平面（需手动指定路径）

用法：
    from scripts.ae_to_blender_bridge import AEToBlenderBridge
    bridge = AEToBlenderBridge()
    bridge.convert("path/to/aep_analysis.json", "output_script.py")
    # 然后运行: blender --background --python output_script.py
"""
from __future__ import annotations

import json
import math
import os
from pathlib import Path
from typing import Any, Dict, List, Optional


class AEToBlenderBridge:
    """AE 工程到 Blender 场景的转换器。"""

    def __init__(self, project_root: Path | None = None) -> None:
        self.project_root = project_root or Path(__file__).resolve().parent.parent
        self._ae_data: dict[str, Any] = {}
        self._script_lines: list[str] = []

    def convert(
        self,
        ae_json_path: str,
        output_script_path: str,
        image_base_dir: str | None = None,
    ) -> str:
        """将 AE 分析 JSON 转换为 Blender Python 脚本。

        Args:
            ae_json_path: AE 分析结果 JSON 文件路径
            output_script_path: 输出的 Blender Python 脚本路径
            image_base_dir: PSD/图像文件的基础目录（可选）

        Returns:
            生成的脚本内容
        """
        with open(ae_json_path, "r", encoding="utf-8") as f:
            self._ae_data = json.load(f)

        self._script_lines = []
        self._add_header()
        self._add_scene_setup()
        self._add_camera()
        self._add_collections_and_objects()
        self._add_materials()
        self._add_render_settings()
        self._add_footer()

        script_content = "\n".join(self._script_lines)

        os.makedirs(os.path.dirname(output_script_path) or ".", exist_ok=True)
        with open(output_script_path, "w", encoding="utf-8") as f:
            f.write(script_content)

        return script_content

    def _add_header(self) -> None:
        """添加脚本头部。"""
        self._script_lines.extend([
            '"""Auto-generated by AE→Blender Bridge"""',
            "import bpy",
            "import math",
            "import os",
            "",
            "# 清除默认场景",
            "bpy.ops.wm.read_factory_settings(use_empty=True)",
            "",
        ])

    def _add_scene_setup(self) -> None:
        """添加场景设置。"""
        project = self._ae_data.get("project", {})
        stats = self._ae_data.get("stats", {})

        # 获取主合成信息
        main_comp = self._find_main_composition()
        if main_comp:
            w, h = main_comp["width"], main_comp["height"]
            fps = main_comp["frameRate"]
            dur = main_comp["duration"]
        else:
            w, h = 1920, 1080
            fps = 24.0
            dur = 10.0

        self._script_lines.extend([
            "# 创建场景",
            f'scene = bpy.data.scenes.new("{project.get("name", "AE_Scene")}")',
            "bpy.context.window.scene = scene",
            "",
            f"scene.render.resolution_x = {w}",
            f"scene.render.resolution_y = {h}",
            f"scene.render.fps = {int(fps)}",
            f"scene.render.fps_base = {1.0 if fps == int(fps) else 1.001:.3f}",
            f"scene.frame_end = int({dur} * {int(fps)})",
            "",
            "# 项目信息（自定义属性）",
            f'scene["ae_project_name"] = "{project.get("name", "untitled")}"',
            f'scene["ae_total_comps"] = {stats.get("totalComps", 0)}',
            f'scene["ae_total_layers"] = {stats.get("totalLayers", 0)}',
            f'scene["ae_total_effects"] = {stats.get("totalEffects", 0)}',
            "",
        ])

    def _add_camera(self) -> None:
        """添加摄像机。"""
        main_comp = self._find_main_composition()
        if not main_comp:
            return

        w, h = main_comp["width"], main_comp["height"]
        # 计算焦距（假设 35mm 传感器）
        aspect = w / h if h > 0 else 1.778
        fov_deg = 50  # 默认 FOV

        self._script_lines.extend([
            "# 摄像机",
            'cam_data = bpy.data.cameras.new("AECamera")',
            "cam = bpy.data.objects.new(\"AECamera\", cam_data)",
            "scene.collection.objects.link(cam)",
            f"cam_data.lens = {35 / (2 * math.tan(math.radians(fov_deg / 2)) * aspect / 2):.2f}  # ~50mm equivalent",
            "cam.location = (0, -10, 0)",
            "cam.rotation_euler = (math.radians(90), 0, 0)",
            "scene.camera = cam",
            "",
        ])

    def _add_collections_and_objects(self) -> None:
        """添加 Collection 层级和对象。"""
        compositions = self._ae_data.get("compositions", [])
        if not compositions:
            return

        self._script_lines.append("# === 合成层级 → Collection ===")
        self._script_lines.append("")

        # 主 Collection
        self._script_lines.extend([
            'main_col = bpy.data.collections.new("AE_Project")',
            "scene.collection.children.link(main_col)",
            "",
        ])

        # 两遍处理：先创建所有对象，再设置父子关系
        parent_refs = []  # (child_var, parent_comp, parent_layer)

        for comp in compositions:
            comp_name = self._sanitize_name(comp["name"])
            self._script_lines.extend([
                f'# --- Comp: {comp_name} ({comp["numLayers"]} layers) ---',
                f'col_{comp_name} = bpy.data.collections.new("{comp_name}")',
                "main_col.children.link(col_" + comp_name + ")",
                "",
            ])

            for layer in comp.get("layers", []):
                layer_name = self._sanitize_name(layer["name"])
                layer_type = layer.get("type", "footage")
                var_name = f"empty_{comp_name}_{layer_name}"

                self._script_lines.append(
                    f'{var_name} = bpy.data.objects.new("{layer_name}", None)'
                )
                self._script_lines.append(
                    f"{var_name}.empty_display_type = 'PLAIN_AXES'"
                )
                self._script_lines.append(
                    f"col_{comp_name}.objects.link({var_name})"
                )

                # 自定义属性
                self._script_lines.append(
                    f'{var_name}["ae_type"] = "{layer_type}"'
                )
                blend = layer.get("blendMode", "normal")
                self._script_lines.append(
                    f'{var_name}["ae_blend_mode"] = "{blend}"'
                )
                opacity = layer.get("opacity", 100)
                self._script_lines.append(
                    f'{var_name}["ae_opacity"] = {opacity}'
                )

                # 记录父子关系（延迟设置）
                parent = layer.get("parent")
                if parent:
                    parent_refs.append((var_name, comp_name, parent["name"]))

                # 源信息
                source = layer.get("source")
                if source and source.get("name"):
                    src_name = source["name"].replace('"', '\\"')
                    self._script_lines.append(
                        f'{var_name}["ae_source"] = "{src_name}"'
                    )

                # 效果信息
                effects = layer.get("effects", [])
                if effects:
                    effect_names = [e["name"].replace('"', '\\"') for e in effects]
                    self._script_lines.append(
                        f'{var_name}["ae_effects"] = "{",".join(effect_names)}"'
                    )

                self._script_lines.append("")

        # 第二遍：设置父子关系（使用 try/except 避免未定义引用）
        if parent_refs:
            self._script_lines.append("# === 父子关系 ===")
            for child_var, comp_name, parent_name in parent_refs:
                parent_var_name = f"empty_{comp_name}_{self._sanitize_name(parent_name)}"
                self._script_lines.append(
                    f"try: {child_var}.parent = {parent_var_name}"
                )
                self._script_lines.append(
                    "except: pass  # parent may not exist"
                )
            self._script_lines.append("")

    def _add_materials(self) -> None:
        """添加基础材质。"""
        self._script_lines.extend([
            "# === 基础材质 ===",
            'mat_default = bpy.data.materials.new("AE_Default")',
            "mat_default.use_nodes = True",
            "bsdf = mat_default.node_tree.nodes.get('Principled BSDF')",
            "if bsdf:",
            "    bsdf.inputs['Base Color'].default_value = (0.8, 0.8, 0.8, 1.0)",
            "",
        ])

    def _add_render_settings(self) -> None:
        """添加渲染设置。"""
        self._script_lines.extend([
            "# === 渲染设置 ===",
            "scene.render.engine = 'BLENDER_EEVEE'",
            "scene.render.film_transparent = True",
            "scene.render.image_settings.file_format = 'PNG'",
            "scene.render.image_settings.color_mode = 'RGBA'",
            "",
        ])

    def _add_footer(self) -> None:
        """添加脚本尾部（保存）。"""
        self._script_lines.extend([
            "# === 完成 ===",
            'print("AE→Blender bridge complete!")',
            'print(f"Collections: {len(bpy.data.collections)}")',
            'print(f"Objects: {len(bpy.data.objects)}")',
            "",
            "# 保存 blend 文件",
            'output_blend = os.path.join(os.path.dirname(__file__), "ae_project.blend")',
            "bpy.ops.wm.save_as_mainfile(filepath=output_blend)",
            'print(f"Saved to: {output_blend}")',
            "",
        ])

    def _find_main_composition(self) -> dict[str, Any] | None:
        """找到主合成（通常是最终输出合成）。"""
        comps = self._ae_data.get("compositions", [])
        if not comps:
            return None

        # 查找 1920x1080 或最大的合成作为主合成
        main = None
        max_layers = 0
        for c in comps:
            if c.get("width") == 1920 and c.get("height") == 1080:
                return c
            if c["numLayers"] > max_layers:
                max_layers = c["numLayers"]
                main = c
        return main or comps[0] if comps else None

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """清理名称，使其可以作为 Python 变量名。"""
        # 替换非字母数字字符为下划线
        result = ""
        for ch in name:
            if ch.isalnum() or ch == "_":
                result += ch
            else:
                result += "_"
        # 确保不以数字开头
        if result and result[0].isdigit():
            result = "_" + result
        # 限制长度
        return result[:40] if len(result) > 40 else result


def main():
    """CLI 入口。"""
    import sys

    if len(sys.argv) < 3:
        print("Usage: python ae_to_blender_bridge.py <ae_analysis.json> <output.py>")
        sys.exit(1)

    json_path = sys.argv[1]
    output_path = sys.argv[2]
    image_dir = sys.argv[3] if len(sys.argv) > 3 else None

    bridge = AEToBlenderBridge()
    script = bridge.convert(json_path, output_path, image_dir)
    print(f"Generated Blender script: {output_path}")
    print(f"Script size: {len(script)} bytes, {len(script.splitlines())} lines")


if __name__ == "__main__":
    main()
